# Generated by Django 5.1 on 2024-08-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0002_speaker_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
