# Generated by Django 5.1 on 2024-08-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0003_speaker_facebook_speaker_instagram_speaker_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='profile',
            field=models.ImageField(default='uploads/profiles/default.jpg', max_length=255, upload_to='uploads/profiles/'),
        ),
    ]
