# Generated by Django 5.1 on 2024-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0004_speaker_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='profile',
            field=models.ImageField(blank=True, default='uploads/profiles/default.jpg', max_length=255, null=True, upload_to='uploads/profiles/'),
        ),
    ]
