# Generated by Django 5.1 on 2024-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0005_alter_speaker_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
