# Generated by Django 5.1 on 2024-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0006_speaker_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[('standard-access', 'Standard Access'), ('pro-access', 'Pro Access'), ('premium-access', 'Premium Access')], max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
