# Generated by Django 5.1 on 2024-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0007_ticketpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
