# Generated by Django 5.1 on 2024-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0008_alter_ticketpurchase_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
