# Generated by Django 5.1 on 2024-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0010_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank='true', max_length=100),
        ),
    ]
