# Generated by Django 5.1 on 2024-08-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0011_galleryimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Event Venue', max_length=255)),
                ('description', models.TextField()),
                ('google_maps_url', models.URLField(help_text='Paste the Google Maps embed URL here', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_gallery/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='EventManager.eventvenue')),
            ],
        ),
    ]
